name: Terraform AWS CI/CD

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

jobs:
  # --------------------------
  # Stage 1: Lint & Validate
  # --------------------------
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.6

      - run: terraform init
      - run: terraform fmt -recursive
      - run: terraform validate

  # --------------------------
  # Stage 2: Plan
  # --------------------------
  plan:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.6

      - run: terraform init
      - run: terraform plan -var-file="terraform.tfvars" -out=tfplan

      - uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: tfplan

  # --------------------------
  # Stage 3: Apply
  # --------------------------
  apply:
    needs: plan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.6

      - run: terraform init

      - uses: actions/download-artifact@v4
        with:
          name: tfplan
          path: .

      - run: terraform apply -auto-approve tfplan

  # --------------------------
  # Stage 4: Optional Tests
  # --------------------------
  test:
    needs: apply
    runs-on: ubuntu-latest
    steps:
      - run: echo "
